version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 1
    schedule:
      interval: "daily"
      time: "02:00"
    target-branch: "master"
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      default-days: 1
    schedule:
      interval: "daily"
      time: "02:00"
    target-branch: "master"
    open-pull-requests-limit: 25
    groups:
      babel:
        patterns:
          - "@babel/*"
      jest:
        patterns:
          - "jest"
          - "jest-cli"
          - "babel-jest"
          - "jest-environment-jsdom"
      playwrite:
        patterns:
          - "@playwrite/*"
          - "playwrite"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-is"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      vitest:
        patterns:
          - "@vitest/*"
          - "vitest"
