version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    target-branch: "master"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    target-branch: "master"
    open-pull-requests-limit: 20
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      babel:
        patterns:
          - "@babel/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      jest:
        patterns:
          - "jest"
          - "jest-cli"
          - "babel-jest"
          - "jest-environment-jsdom"
