import {
  METRIC_TYPE_FILE_SIZE,
  METRIC_TYPE_NUMERIC,
  METRIC_TYPE_PERCENTAGE,
} from '../config/metrics';
import { MetricId, SizeByTypeMetricId } from './constants';

export const metrics = {
  [MetricId.BundleSize]: {
    label: 'Bundle Size',
    description: 'Sum of all assets emitted by webpack.',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: METRIC_TYPE_FILE_SIZE,
  },
  [MetricId.TotalInitialSizeJS]: {
    label: 'Initial JS',
    description: 'Sum of all JavaScript assets that are labeled as initial(eg: vendor.js, app.js).',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: METRIC_TYPE_FILE_SIZE,
  },
  [MetricId.TotalInitialSizeCSS]: {
    label: 'Initial CSS',
    description: 'Sum of all CSS assets that are labeled as initial(eg: vendor.css, app.css).',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: METRIC_TYPE_FILE_SIZE,
  },
  [MetricId.CacheInvalidation]: {
    label: 'Cache Invalidation',
    description: 'Ratio between the total changed assets and Bundle Size.',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: METRIC_TYPE_PERCENTAGE,
    biggerIsBetter: false,
  },
  [MetricId.ChunkCount]: {
    label: 'Chunks',
    description: 'Total number of chunks generated by webpack.',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: METRIC_TYPE_NUMERIC,
    biggerIsBetter: false,
  },
  [MetricId.AssetCount]: {
    label: 'Assets',
    description: 'Total number of assets emitted by webpack.',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: METRIC_TYPE_NUMERIC,
    biggerIsBetter: false,
  },
  [MetricId.ModuleName]: {
    label: 'Modules',
    description: 'Total number of modules bundled by webpack.',
    url: 'https://relative-ci.com/documentation/metrics-and-data#modules-1',
    type: METRIC_TYPE_NUMERIC,
    biggerIsBetter: false,
  },
  [MetricId.PackageCount]: {
    label: 'Packages',
    description: 'Total number of packages bundled by webpack.',
    url: 'https://relative-ci.com/documentation/metrics-and-data#packages',
    type: METRIC_TYPE_NUMERIC,
    biggerIsBetter: false,
  },
  [MetricId.DuplicatePackagesCount]: {
    label: 'Duplicate Packages',
    description: 'Total number of packages that are duplicated.',
    url: 'https://relative-ci.com/documentation/metrics-and-data#packages',
    type: METRIC_TYPE_NUMERIC,
    biggerIsBetter: false,
  },
  sizes: {
    [SizeByTypeMetricId.JS]: {
      label: 'JS',
      type: METRIC_TYPE_FILE_SIZE,
    },
    [SizeByTypeMetricId.CSS]: {
      label: 'CSS',
      type: METRIC_TYPE_FILE_SIZE,
    },
    [SizeByTypeMetricId.IMG]: {
      label: 'IMG',
      type: METRIC_TYPE_FILE_SIZE,
    },
    [SizeByTypeMetricId.Media]: {
      label: 'Media',
      type: METRIC_TYPE_FILE_SIZE,
    },
    [SizeByTypeMetricId.Font]: {
      label: 'Fonts',
      type: METRIC_TYPE_FILE_SIZE,
    },
    [SizeByTypeMetricId.HTML]: {
      label: 'HTML',
      type: METRIC_TYPE_FILE_SIZE,
    },
    [SizeByTypeMetricId.Other]: {
      label: 'Other',
      type: METRIC_TYPE_FILE_SIZE,
    },
  },
};
