import { FILE_TYPE_LABELS } from '../config/file-types';
import { Metric } from './types';
import { MetricTypeType } from '../constants';

interface WebpackMetricConfig {
  label: string;
  description?: string;
  url?: string;
  type: MetricTypeType;
  /**
   * Increased values are regressions, decreased values are improvements
   */
  biggerIsBetter?: boolean;
  /**
   * Do not show the delta
   */
  skipDelta?: boolean;
}

type WebpackMetrics = Partial<Record<Metric, WebpackMetricConfig>> & {
  sizes: Partial<Record<Metric, WebpackMetricConfig>>;
};

export const metrics: WebpackMetrics = {
  [Metric.BUNDLE_SIZE]: {
    label: 'Bundle Size',
    description: 'The total file size of the assets generated or processed by the bundler',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
  },
  [Metric.INITIAL_SIZE_JS]: {
    label: 'Initial JS',
    description: 'The total file size of the JavaScript initial chunks',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
  },
  [Metric.INITIAL_SIZE_CSS]: {
    label: 'Initial CSS',
    description: 'The total file size of the CSS initial chunks',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
  },
  [Metric.CACHE_INVALIDATION]: {
    label: 'Cache Invalidation',
    description:
      'The ratio between the total of the changed assets and the total file size(Bundle Size)',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: MetricTypeType.METRIC_TYPE_PERCENTAGE,
    biggerIsBetter: undefined,
    skipDelta: true,
  },
  [Metric.CHUNK_COUNT]: {
    label: 'Chunks',
    description: 'The total number of chunks generated by the bundler',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: MetricTypeType.METRIC_TYPE_NUMERIC,
    biggerIsBetter: undefined,
  },
  [Metric.ASSET_COUNT]: {
    label: 'Assets',
    description: 'Total number of assets generated or produced by the bundler',
    url: 'https://relative-ci.com/documentation/metrics-and-data#assets',
    type: MetricTypeType.METRIC_TYPE_NUMERIC,
    biggerIsBetter: undefined,
  },
  [Metric.MODULE_COUNT]: {
    label: 'Modules',
    description: 'The total number of bundled modules',
    url: 'https://relative-ci.com/documentation/metrics-and-data#modules-1',
    type: MetricTypeType.METRIC_TYPE_NUMERIC,
    biggerIsBetter: undefined,
  },
  [Metric.DUPLICATE_MODULES_COUNT]: {
    label: 'Duplicate Modules',
    description: 'The total number of modules that belong to more than one chunk',
    url: 'https://relative-ci.com/documentation/metrics-and-data#modules-1',
    type: MetricTypeType.METRIC_TYPE_NUMERIC,
    biggerIsBetter: false,
  },
  [Metric.DUPLICATE_CODE]: {
    label: 'Duplicate Code',
    description: 'The percentage of total duplicate module size from the total module size',
    url: 'https://relative-ci.com/documentation/metrics-and-data#modules-1',
    type: MetricTypeType.METRIC_TYPE_PERCENTAGE,
    biggerIsBetter: false,
  },
  [Metric.PACKAGE_COUNT]: {
    label: 'Packages',
    description: 'The total number of bundled packages',
    url: 'https://relative-ci.com/documentation/metrics-and-data#packages',
    type: MetricTypeType.METRIC_TYPE_NUMERIC,
    biggerIsBetter: false,
  },
  [Metric.DUPLICATE_PACKAGES_COUNT]: {
    label: 'Duplicate Packages',
    description: 'The total number of duplicate packages',
    url: 'https://relative-ci.com/documentation/metrics-and-data#packages',
    type: MetricTypeType.METRIC_TYPE_NUMERIC,
    biggerIsBetter: false,
  },
  sizes: {
    [Metric.TOTAL_SIZE_JS]: {
      label: FILE_TYPE_LABELS.JS,
      type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
    },
    [Metric.TOTAL_SIZE_CSS]: {
      label: FILE_TYPE_LABELS.CSS,
      type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
    },
    [Metric.TOTAL_SIZE_IMG]: {
      label: FILE_TYPE_LABELS.IMG,
      type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
    },
    [Metric.TOTAL_SIZE_MEDIA]: {
      label: FILE_TYPE_LABELS.MEDIA,
      type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
    },
    [Metric.TOTAL_SIZE_FONT]: {
      label: FILE_TYPE_LABELS.FONT,
      type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
    },
    [Metric.TOTAL_SIZE_HTML]: {
      label: FILE_TYPE_LABELS.HTML,
      type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
    },
    [Metric.TOTAL_SIZE_OTHER]: {
      label: FILE_TYPE_LABELS.OTHER,
      type: MetricTypeType.METRIC_TYPE_FILE_SIZE,
    },
  },
};
