export const DELTA_TYPE_NEGATIVE = 'NEGATIVE';
export const DELTA_TYPE_NO_CHANGE = 'NO_CHANGE';
export const DELTA_TYPE_POSITIVE = 'POSITIVE';

export const DELTA_TYPE_LEVEL_LOW = 'LOW';
export const DELTA_TYPE_LEVEL_HIGH = 'HIGH';

export const DELTA_TYPE_LOW_NEGATIVE = `${DELTA_TYPE_LEVEL_LOW}_${DELTA_TYPE_NEGATIVE}`;
export const DELTA_TYPE_HIGH_NEGATIVE = `${DELTA_TYPE_LEVEL_HIGH}_${DELTA_TYPE_NEGATIVE}`;
export const DELTA_TYPE_LOW_POSITIVE = `${DELTA_TYPE_LEVEL_LOW}_${DELTA_TYPE_POSITIVE}`;
export const DELTA_TYPE_HIGH_POSITIVE = `${DELTA_TYPE_LEVEL_HIGH}_${DELTA_TYPE_POSITIVE}`;
