module.exports = {
  builtAt: 1546300800000,
  hash: 'defg1234',
  assets: [
    {
      chunkNames: ['main'],
      chunks: [1],
      emitted: true,
      name: 'main.css',
      size: 11000,
    },
    {
      chunkNames: ['main'],
      chunks: [1],
      emitted: true,
      name: 'main.css.map',
      size: 28041,
    },
    {
      chunkNames: ['main'],
      chunks: [1],
      emitted: true,
      name: 'main.js',
      size: 49000,
    },
    {
      chunkNames: ['main'],
      chunks: [1],
      emitted: true,
      name: 'main.js.map',
      size: 10000,
    },
    {
      chunkNames: [],
      chunks: [],
      emitted: true,
      name: 'logo.png',
      size: 1000,
    },
    {
      chunkNames: [],
      chunks: [],
      emitted: true,
      name: 'index.html',
      size: 2000,
    },
  ],
  chunks: [
    {
      children: [],
      childrenByOrder: {},
      entry: true,
      filteredModules: 0,
      hash: '2c2ca373295fea0a2cc8',
      id: 1,
      initial: true,
      modules: [],
      files: ['main.css', 'main.js'],
      names: ['main'],
      origins: [],
      parents: [],
      rendered: true,
      siblings: [1],
      size: 60000,
    },
  ],
  modules: [
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'module-a',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'module-b',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1500,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'node_modules/package-a/index.js',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'node_modules/package-b/index.js',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'node_modules/package-c/index.js',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
  ],
};
