module.exports = {
  builtAt: 1546300800000,
  hash: 'abcd1234',
  assets: [
    {
      chunkNames: ['main'],
      chunks: [1],
      emitted: true,
      name: 'main.a1b2c3.css',
      size: 10000,
    },
    {
      chunkNames: ['main'],
      chunks: [1],
      emitted: true,
      name: 'main.a1b2c3.css.map',
      size: 28041,
    },
    {
      chunkNames: ['main'],
      chunks: [1],
      emitted: true,
      name: 'main.a2b3c4.js',
      size: 50000,
    },
    {
      chunkNames: ['main'],
      chunks: [1],
      emitted: true,
      name: 'main.a2b3c4.js.map',
      size: 10000,
    },
    {
      chunkNames: [],
      chunks: [],
      emitted: true,
      name: 'logo.a3b4c5.png',
      size: 1000,
    },
    {
      chunkNames: [],
      chunks: [],
      emitted: true,
      name: 'index.html',
      size: 2000,
    },
  ],
  chunks: [
    {
      children: [],
      childrenByOrder: {},
      entry: true,
      filteredModules: 0,
      hash: '2c2ca373295fea0a2cc8',
      id: 1,
      initial: true,
      modules: [],
      files: [
        'main.a1b2c3.css',
        'main.a2b3c4.js',
      ],
      names: ['main'],
      origins: [],
      parents: [],
      rendered: true,
      siblings: [1],
      size: 60000,
    },
  ],
  entrypoints: {
    main: {
      assets: [
        'main.a1b2c3.css',
        'main.a1b2c3.css.map',
        'main.a2b3c4.js',
        'main.a2b3c4.js.map',
      ],
      childAssets: {},
      children: {},
      chunks: [1, 0],
    },
  },
  modules: [
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'module-a',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'module-b',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 2000,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'node_modules/package-a/index.js',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'node_modules/package-a/node_modules/package-c/index.js',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'node_modules/package-b/index.js',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
    {
      assets: [],
      built: true,
      cacheable: true,
      chunks: [1],
      depth: 11,
      errors: 0,
      failed: false,
      id: 0,
      index: 500,
      index2: 491,
      issuerId: null,
      issuerPath: [],
      name: 'node_modules/package-c/index.js',
      optional: false,
      prefetched: false,
      providedExports: null,
      size: 1000,
      usedExports: true,
      warnings: 0,
    },
  ],
};
